name: Test SSH to GCP VM

on:
  workflow_dispatch:  # lets you trigger manually from GitHub UI

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Connect and run test command
        run: |
          run: |
                ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
                echo "Pulling latest code..."
                cd playground_api
                git pull origin main
                chmod +x deploy.sh
                cd ..
                ./deploy.sh
                EOF
