name: CI - Playground API

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
    branches: [ main ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'
          cache: 'pip'
      
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.11.13
      
      - name: Run Ruff linter
        run: ruff check .

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/uv.lock', '**/pyproject.toml') }}
          restore-keys: uv-${{ runner.os }}-
      
      - name: Create virtual environment and install dependencies
        run: uv pip install pytest==8.3.5

      - name: Run run.py test
        run: uv run pytest tests/test_run.py -v
      - name: Run face test
        run: uv run pytest tests/test_face.py -v
      - name: Run ocr test
        run: uv run pytest tests/test_ocr.py -v
      
      - name: Clean up
        if: always()
        run: |
          rm -rf .venv
          rm -rf ~/.cache/uv
